[0.019s] Invoking command in '/home/sudheer/ros2_ws/build/my_robot_interfaces': CMAKE_PREFIX_PATH=/home/sudheer/ros2_ws/install/my_py_pkg:/opt/ros/humble /usr/bin/cmake --build /home/sudheer/ros2_ws/build/my_robot_interfaces -- -j4 -l4
[0.078s] -- Found ament_cmake: 1.3.8 (/opt/ros/humble/share/ament_cmake/cmake)
[0.259s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.261s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.265s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.307s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.588s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.588s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.588s]   my_robot_interfaces --arguments-file
[0.588s]   /home/sudheer/ros2_ws/build/my_robot_interfaces/rosidl_adapter__arguments__my_robot_interfaces.json
[0.588s]   --output-dir
[0.588s]   /home/sudheer/ros2_ws/build/my_robot_interfaces/rosidl_adapter/my_robot_interfaces
[0.588s]   --output-file
[0.589s]   /home/sudheer/ros2_ws/build/my_robot_interfaces/rosidl_adapter/my_robot_interfaces.idls)
[0.589s]   returned error code 1:
[0.589s] 
[0.589s]   Traceback (most recent call last):
[0.589s] 
[0.589s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.589s]       return _run_code(code, main_globals, None,
[0.589s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.589s]       exec(code, run_globals)
[0.589s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.589s]       sys.exit(main())
[0.589s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.590s]       abs_idl_file = convert_to_idl(
[0.590s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[0.590s]       return convert_srv_to_idl(
[0.590s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[0.590s]       srv = parse_service_string(package_name, input_file.stem, content)
[0.590s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 859, in parse_service_string
[0.590s]       request_message = parse_message_string(
[0.590s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.590s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.590s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.590s]       self.base_type = BaseType(
[0.590s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.590s]       raise InvalidResourceName(
[0.591s] 
[0.591s]   rosidl_adapter.parser.InvalidResourceName: 'server_Request' is an invalid
[0.591s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.591s] 
[0.591s] Call Stack (most recent call first):
[0.591s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.591s]   CMakeLists.txt:16 (rosidl_generate_interfaces)
[0.591s] 
[0.591s] [0m
[0.591s] -- Configuring incomplete, errors occurred!
[0.591s] See also "/home/sudheer/ros2_ws/build/my_robot_interfaces/CMakeFiles/CMakeOutput.log".
[0.598s] gmake: *** [Makefile:747: cmake_check_build_system] Error 1
[0.602s] Invoked command in '/home/sudheer/ros2_ws/build/my_robot_interfaces' returned '2': CMAKE_PREFIX_PATH=/home/sudheer/ros2_ws/install/my_py_pkg:/opt/ros/humble /usr/bin/cmake --build /home/sudheer/ros2_ws/build/my_robot_interfaces -- -j4 -l4
